[package]
name = "wtf"
version = "0.1.0"
authors = ["monkeyinastripedshirt@gmail.com <monkeyinastripedshirt@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.5.14"

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }